#!/bin/bash
###############################################
# Shell Wrapper to start/stop/restart mqirc
wdir=/home/mqirc/bin
pidfile=$wdir/mqirc.pid



cd $wdir

start(){
python mqirc.py
if [[ "$?" -eq "0" ]] ; then echo Success ; else echo Failed;fi
}

start_daemon(){
echo 'Starting mqirc'
python mqirc.py > /dev/null 2>&1 & echo "$!" >$pidfile
if [[ "$?" -eq "0" ]] ; then echo Success ; else echo Failed;fi
}

stop(){
echo 'Killing mqirc'
kill $(cat $pidfile) >/dev/null 2>&1
if [[ "$?" -eq "0" ]] ; then echo Success ; else echo Failed;fi
}


case "$@" in -k|--kill)
stop
;;

-r|--restart)
stop
start_daemon
;;

-h|--help)
echo 'MqIRC Wrapper'
echo '-- Usage: --'
echo 'mqirc <-d|--daemon><-s|--start><-r|--restart><-k|--kill>'

;;
-d|--daemon)
start_daemon
;;
-s|--start|*)
start
;;

esac

exit
