#!/bin/bash
###############################################
echo "Bash wrapper script for mqirc"

wdir=/home/mqirc/bin
pidfile=$wdir/mqirc.pid



cd $wdir

start(){
echo 'Starting mqirc'
python mqirc.py >> mqirc.log 2>&1 & echo "$!" >$pidfile
if [[ "$?" -eq "0" ]] ; then echo Success ; else echo Failed;fi
}

stop(){
echo 'Killing mqirc'
kill $(cat $pidfile) >/dev/null 2>&1
if [[ "$?" -eq "0" ]] ; then echo Success ; else echo Failed;fi
}


case "$@" in -k|--kill)
stop
;;

-r|--restart)
stop
start
;;

-h|--help)
echo 'MqIRC Wrapper'
echo '-- Usage: --'
echo 'mqirc <-s|--start><-r|--restart><-k|--kill>'

;;

-s|--start|*)
start
;;

esac

exit
